# Use root/example as user/password credentials

version: '3.6'

services:

  mysql:
    container_name: mysql
    image: mymysql
    command: mysqld --user=root
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=mydb

  tomcat:
    image: tomcat
    restart: always
    ports:
      - 8001:8080
    volumes:
      - /data/mydocker1/war/employees.war:/usr/local/tomcat/webapps/myapp.war
    links:
      - mysql
